[package]
name = "eth2"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.52"
types = { path = "../../consensus/types" }
hex = "0.4.2"
reqwest = { version = "0.10.8", features = ["json"] }
eth2_libp2p = { path = "../../beacon_node/eth2_libp2p" }
proto_array = { path = "../../consensus/proto_array", optional = true }
serde_utils = { path = "../../consensus/serde_utils" }
sysinfo = "0.15.2"
systemstat = "0.1.5"

[target.'cfg(target_os = "linux")'.dependencies]
psutil = { version = "3.1.0", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
psutil = "3.1.0"

[features]
default = ["lighthouse"]
lighthouse = ["proto_array", "psutil"]
