on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

jobs:
  cargo-fmt:
    name: cargo-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Check formatting with cargo fmt
      run: make cargo-fmt
  arbitrary-check:
    name: arbitrary-check
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
    - uses: actions/checkout@v1
    - name: Validate state_processing feature arbitrary-fuzz
      run:  make arbitrary-fuzz
